### ISSUE TITLE
Fix Encoding::CompatibilityError when ASCII/UTF-8 is used

### ISSUE THREAD

**Issue by tomav** [tomav/steam_hlds_log_parser#2]
Seems that ASCII characters are breaking GSUB method on i18n interpolation.

```
  => data: {:type=>"disconnect", :params=>{:player=>"C'est pas des g\xC3\xA2teaux \xC3\xA7a", :player_team=>"CT"}}
  ## 0.0.0.0:27035 => HLDS s'est déconnecté ?
  /home/cstrike/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/i18n-0.6.4/lib/i18n/interpolate/ruby.rb:19:in `gsub': incompatible character encodings: ASCII-8BIT and UTF-8 (Encoding::CompatibilityError)
          from /home/cstrike/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/i18n-0.6.4/lib/i18n/interpolate/ruby.rb:19:in `interpolate_hash'
          from /home/cstrike/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/i18n-0.6.4/lib/i18n/interpolate/ruby.rb:15:in `interpolate'
          from /home/cstrike/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/i18n-0.6.4/lib/i18n/backend/base.rb:148:in `interpolate'
          from /home/cstrike/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/i18n-0.6.4/lib/i18n/backend/base.rb:41:in `translate'
          from /home/cstrike/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/i18n-0.6.4/lib/i18n.rb:156:in `block in translate'
          from /home/cstrike/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/i18n-0.6.4/lib/i18n.rb:152:in `catch'
          from /home/cstrike/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/i18n-0.6.4/lib/i18n.rb:152:in `translate'
          from /home/cstrike/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/steam_hlds_log_parser-0.5.3/lib/steam_hlds_log_parser/displayer.rb:33:in `get_translation'
          from plop.rb:10:in `initialize'
          from /home/cstrike/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/steam_hlds_log_parser-0.5.3/lib/steam_hlds_log_parser/handler.rb:101:in `new'
          from /home/cstrike/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/steam_hlds_log_parser-0.5.3/lib/steam_hlds_log_parser/handler.rb:101:in `receive_data'
          from /home/cstrike/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
          from /home/cstrike/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
          from /home/cstrike/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/steam_hlds_log_parser-0.5.3/lib/steam_hlds_log_parser/client.rb:52:in `start'
          from plop.rb:32:in `<main>'
```

**Comment by tomav** [comment]
Another one:

```
=> data: {:type=>"disconnect", :params=>{:player=>"Peter le ma\xC3\xAEtre des dragons", :player_team=>"TE"}}
## 0.0.0.0:27035 => HLDS s'est déconnecté ?
/home/cstrike/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/i18n-0.6.4/lib/i18n/interpolate/ruby.rb:19:in `gsub': incompatible character encodings: ASCII-8BIT and UTF-8 (Encoding::CompatibilityError)
        from /home/cstrike/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/i18n-0.6.4/lib/i18n/interpolate/ruby.rb:19:in `interpolate_hash'
        from /home/cstrike/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/i18n-0.6.4/lib/i18n/interpolate/ruby.rb:15:in `interpolate'
        from /home/cstrike/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/i18n-0.6.4/lib/i18n/backend/base.rb:148:in `interpolate'
        from /home/cstrike/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/i18n-0.6.4/lib/i18n/backend/base.rb:41:in `translate'
        from /home/cstrike/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/i18n-0.6.4/lib/i18n.rb:156:in `block in translate'
        from /home/cstrike/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/i18n-0.6.4/lib/i18n.rb:152:in `catch'
        from /home/cstrike/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/i18n-0.6.4/lib/i18n.rb:152:in `translate'
        from /home/cstrike/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/steam_hlds_log_parser-0.5.3/lib/steam_hlds_log_parser/displayer.rb:33:in `get_translation'
        from hlds.rb:10:in `initialize'
        from /home/cstrike/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/steam_hlds_log_parser-0.5.3/lib/steam_hlds_log_parser/handler.rb:101:in `new'
        from /home/cstrike/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/steam_hlds_log_parser-0.5.3/lib/steam_hlds_log_parser/handler.rb:101:in `receive_data'
        from /home/cstrike/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
        from /home/cstrike/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
        from /home/cstrike/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/steam_hlds_log_parser-0.5.3/lib/steam_hlds_log_parser/client.rb:52:in `start'
        from hlds.rb:32:in `<main>'
```
